### ISSUE TITLE
验证集效果太差

### ISSUE THREAD

**Issue by ygk09** [GaoQ1/rasa-nlp-architect#1]
大神你好，按readme中写的步骤训练网络，我发现模型在训练集上逐渐收敛，但在验证集上效果很差，几乎没有任何效果，这可能是什么原因？

**Comment by GaoQ1** [comment]
可以把结果贴出来看看。说实话这个我并没有怎么去验证。

**Comment by ygk09** [comment]
98957/98957 [==============================] - 235s 2ms/step - loss: 0.1433 - intent_classifier_output_loss: 0.0053 - intent_slot_crf_loss: 0.1380 - intent_classifier_output_categorical_accuracy: 0.9984 - intent_slot_crf_accuracy: 0.9979 - val_loss: 67.6755 - val_intent_classifier_output_loss: 0.0059 - val_intent_slot_crf_loss: 67.6696 - val_intent_classifier_output_categorical_accuracy: 0.9983 - val_intent_slot_crf_accuracy: 0.2509

**Comment by ygk09** [comment]
用的是MLT模型

**Comment by ygk09** [comment]
还比如有结果：
{
    "intent": {
        "name": "response_family_history",
        "confidence": 1
    },
    "entities": [
        {
            "start": 1,
            "end": 2,
            "entity": "head_symptom",
            "value": "的",
            "confidence": 1
        },
        {
            "start": 2,
            "end": 7,
            "entity": "patient",
            "value": "爷爷奶奶也",
            "confidence": 1
        },
        {
            "start": 7,
            "end": 12,
            "entity": "patient",
            "value": "是耳朵脓痂",
            "confidence": 1
        }
    ],
    "text": "我的爷爷奶奶也是耳朵脓痂"
}

**Comment by GaoQ1** [comment]
这个问题，我周末看一下。intel的这个项目我是为了测试第三方nlu模型怎么配合使用rasa-core的。真正项目中用的话还是用的[rasa-nlu-gao](https://github.com/GaoQ1/rasa_nlu_gq)，里面可以实践下不同的组件。[rasa_chatbot_cn](https://github.com/GaoQ1/rasa_chatbot_cn) 这个demo都有过测试，包括我写的笔记都说的比较详细。

**Comment by ygk09** [comment]
好的，谢谢大神。另外……rasa-nlu-gao里有实体识别和槽填充的联合模型吗？我好像没找到。

**Comment by GaoQ1** [comment]
实体识别和slot filling是分开component做的，rasa-nlu-gao里面没有，[ner-slot_filling](https://github.com/GaoQ1/ner-slot_filling)这个做了
